### ISSUE TITLE
Adding nw.js support

### ISSUE THREAD

**Issue by RSATom** [unbornchikken/cmake-js#3]
%subj%

**Comment by unbornchikken** [comment]
Dunno, aint tried. By theory, yes. I'll give it a try, and fix any compatibility issues arise. Feed you back soon.

**Comment by RSATom** [comment]
Thank you. I'm looking forward to it.

**Comment by unbornchikken** [comment]
For full nw.js compatibility there should be some minor work done. It already works on non Windows systems when you have io.js installed. However, if you're on Windows or using Node.js anywhere CMake.js based builds won't work.

Because it's might be a popular demand, I'm planning to add direct support to CMake.js, and by using that future version, your modules will work with any version of node.js, io.js or nw.js. There won't be nw-gyp like magic required. I don't have timings yet, but v1.0.0 will contain this feature definitely. Stay tuned, I'll inform you with the state of the development in this thread. Maybe you could help me to test this feature, because I'm noob with nw.js.

**Comment by RSATom** [comment]
Thank you. It will be great! I'm starting new project right now (which tends to be pretty popular I hope), so I will be able test it pretty well on all platforms.

**Comment by unbornchikken** [comment]
It's done. See there: https://github.com/unbornchikken/cmake-js#runtimes

There is nothing to do on the module side, all CMake.js 0.9.5+ based modules are compatible with nw.js. Just put the described setting in your nw.js app's package.json, and that's it. It won't affect anything else just CMake.js based dependencies in all level.

**Comment by unbornchikken** [comment]
The third tutorial is in progress, I don't have time for it right now. But there will be nothing else other than that is in the readme right now, just brief. I'm closing this thread. If you have any issues or questions with nw.js compatibility, please open up another thread.

**Comment by RSATom** [comment]
Thank you very much! Will try it soon!
